### ISSUE TITLE
The Odin Project

### ISSUE THREAD

**Issue by harrythomson1** [jdsoteldo/simplycoders-further#1]
I used this website a lot when I was starting out and absolutely loved it. It has a full stack Ruby on Rails pathway and is completely free. It takes people from learning nothing about code to teaching them HTML, CSS, JavaScript, Ruby and ultimately Ruby on Rails. You build projects throughout to. For me, it was all I needed to get myself interested in coding.

https://www.theodinproject.com/

**Comment by jdsoteldo** [comment]
Hello @harrythomson1 thanks for the recommendation, I think we all in one moment or another came across the odin project, great resource, I will make sure to add it!
